# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/setup-tinytex@v2
      - run: tlmgr --version
      
      - name: Install additional LaTeX packages
        run: |
          tlmgr install ae amscls amsfonts amsmath atbegshi atveryend auxhook babel bibtex bigintcalc bitset booktabs caption changepage cm colortbl ctablestack dehyph dvipdfmx dvips ec epstopdf-pkg eso-pic etex etexcmds etoolbox euenc everyshi fancyhdr fancyvrb filehook firstaid float fontspec forarray framed geometry gettitlestring glyphlist graphics graphics-cfg graphics-def grfext grffile helvetic hycolor hyperref hyph-utf8 hyphen-base iftex inconsolata infwarerr intcalc jknapltx knuth-lib kpathsea kvdefinekeys kvoptions kvsetkeys l3backend l3kernel l3packages lastpage latex latex-amsmath-dev latex-bin latex-fonts latex-tools-dev latexconfig latexdiff latexmk letltxmacro lineno lm lm-math ltxcmds lua-alt-getopt lua-uni-algos luahbtex lualatex-math lualibs luaotfload luatex luatexbase makeindex marvosym mdwtools metafont mfware microtype modes natbib oberdiek pdfescape pdflscape pdfpages pdftex pdftexcmds plain psnfss refcount rerunfilecheck rsfs scheme-infraonly selnolig stringenc symbol tex tex-ini-files texlive-scripts texlive.infra thumbpdf times tipa tlgs tlperl tools ucs ulem unicode-data unicode-math uniquecounter url xcolor xetex xetexconfig xkeyval xstring xunicode zapfchan zapfding
          tlmgr list --only-installed

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
